version: "3.9"

networks:
  net1:

services:
  load_balancer:
    build: ./load_balancer
    image: lb-image
    container_name: load_balancer
    ports:
      - "5000:5000"
    networks:
      - net1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: ./server
    image: server-image
    container_name: Server1
    environment:
      - SERVER_ID=1
    networks:
      net1:
        aliases:
          - Server1

  server2:
    build: ./server
    image: server-image
    container_name: Server2
    environment:
      - SERVER_ID=2
    networks:
      net1:
        aliases:
          - Server2

  server3:
    build: ./server
    image: server-image
    container_name: Server3
    environment:
      - SERVER_ID=3
    networks:
      net1:
        aliases:
          - Server3
