FROM python:3.9-slim

WORKDIR /app

COPY load_balancer.py .
COPY consistent_hash.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "load_balancer.py"]