version: "3.9"
services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.load_balancer
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - load_balancer_network
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=0
    networks:
      - load_balancer_network
  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=1
    networks:
      - load_balancer_network
  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=2
    networks:
      - load_balancer_network
networks:
  load_balancer_network:
    driver: bridge